version: '3.2'

services:
    nginx:
        build: ./docker/nginx
        image: rverdin/ci_examen_verdin_nginx:2.0
        expose:
            - 443
        depends_on:
            - php
        environment:
            DOMAIN_NAME: default:localhost
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/srv/:ro
        ports:
            - 80:80
            - 443:443

    php:
        build: ./docker/php
        image: rverdin/ci_examen_verdin_php:2.0
        working_dir: /srv
        volumes:
            - ./:/srv/

    jenkins:
        build:
            context:
                ./docker/jenkins
        ports:
            - 8080:8080