version: '3.2'

services:
    nginx:
        image: nginx:1.15.3-alpine
        expose:
            - 443
        depends_on:
            - php
        environment:
            DOMAIN_NAME: default:localhost
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/srv/:ro
        ports:
            - 80:80
            - 443:443

    php:
        image: php:7.2.10-fpm-alpine3.7
        working_dir: /srv
        volumes:
            - ./:/srv/

    jenkins:
        build:
            context:
                ./docker/jenkins
        ports:
            - 8080:8080