version: '3.2'

services:
    nginx:
        build: ./docker/nginx
        image: rverdin/ci_examen_verdin_nginx:3.0
        expose:
            - 443
        depends_on:
            - php
        environment:
            DOMAIN_NAME: default:localhost
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/srv/:ro
        ports:
            - 80:80
            - 443:443
        links:
            - db

    php:
        build: ./docker/php
        image: rverdin/ci_examen_verdin_php:3.0
        working_dir: /srv
        volumes:
            - ./:/srv/
        links:
            - db
        depends_on:
            - db

    jenkins:
        build:
            context:
                ./docker/jenkins
        ports:
            - 8080:8080
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock

    db:
        build: ./docker/mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database
            - MYSQL_USER=php_user
            - MYSQL_PASSWORD=sdrugntqqsciur
        volumes:
            - mariadb:/var/lib/mysql

volumes:
  mariadb: ~